/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LegalNoticeRouteImport } from './routes/legal-notice'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeIndexRouteImport } from './routes/de/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DeSlugRouteImport } from './routes/de/$slug'
import { Route as ApiVisitRouteImport } from './routes/api/visit'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTerritoriesIndexRouteImport } from './routes/admin/territories/index'
import { Route as AdminOwnersIndexRouteImport } from './routes/admin/owners/index'
import { Route as AdminCampaignsIndexRouteImport } from './routes/admin/campaigns/index'
import { Route as AdminPagesNewRouteImport } from './routes/admin/pages/new'
import { Route as AdminPagesPageIdRouteImport } from './routes/admin/pages/$pageId'

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalNoticeRoute = LegalNoticeRouteImport.update({
  id: '/legal-notice',
  path: '/legal-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeIndexRoute = DeIndexRouteImport.update({
  id: '/de/',
  path: '/de/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DeSlugRoute = DeSlugRouteImport.update({
  id: '/de/$slug',
  path: '/de/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisitRoute = ApiVisitRouteImport.update({
  id: '/api/visit',
  path: '/api/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTerritoriesIndexRoute = AdminTerritoriesIndexRouteImport.update({
  id: '/territories/',
  path: '/territories/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOwnersIndexRoute = AdminOwnersIndexRouteImport.update({
  id: '/owners/',
  path: '/owners/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCampaignsIndexRoute = AdminCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesNewRoute = AdminPagesNewRouteImport.update({
  id: '/pages/new',
  path: '/pages/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesPageIdRoute = AdminPagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/visit': typeof ApiVisitRoute
  '/de/$slug': typeof DeSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/de/': typeof DeIndexRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/campaigns/': typeof AdminCampaignsIndexRoute
  '/admin/owners/': typeof AdminOwnersIndexRoute
  '/admin/territories/': typeof AdminTerritoriesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/visit': typeof ApiVisitRoute
  '/de/$slug': typeof DeSlugRoute
  '/admin': typeof AdminIndexRoute
  '/de': typeof DeIndexRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/campaigns': typeof AdminCampaignsIndexRoute
  '/admin/owners': typeof AdminOwnersIndexRoute
  '/admin/territories': typeof AdminTerritoriesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/visit': typeof ApiVisitRoute
  '/de/$slug': typeof DeSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/de/': typeof DeIndexRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/campaigns/': typeof AdminCampaignsIndexRoute
  '/admin/owners/': typeof AdminOwnersIndexRoute
  '/admin/territories/': typeof AdminTerritoriesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$slug'
    | '/legal-notice'
    | '/privacy-policy'
    | '/admin/login'
    | '/api/visit'
    | '/de/$slug'
    | '/admin/'
    | '/de/'
    | '/admin/pages/$pageId'
    | '/admin/pages/new'
    | '/admin/campaigns/'
    | '/admin/owners/'
    | '/admin/territories/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/legal-notice'
    | '/privacy-policy'
    | '/admin/login'
    | '/api/visit'
    | '/de/$slug'
    | '/admin'
    | '/de'
    | '/admin/pages/$pageId'
    | '/admin/pages/new'
    | '/admin/campaigns'
    | '/admin/owners'
    | '/admin/territories'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$slug'
    | '/legal-notice'
    | '/privacy-policy'
    | '/admin/login'
    | '/api/visit'
    | '/de/$slug'
    | '/admin/'
    | '/de/'
    | '/admin/pages/$pageId'
    | '/admin/pages/new'
    | '/admin/campaigns/'
    | '/admin/owners/'
    | '/admin/territories/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  LegalNoticeRoute: typeof LegalNoticeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ApiVisitRoute: typeof ApiVisitRoute
  DeSlugRoute: typeof DeSlugRoute
  DeIndexRoute: typeof DeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-notice': {
      id: '/legal-notice'
      path: '/legal-notice'
      fullPath: '/legal-notice'
      preLoaderRoute: typeof LegalNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/': {
      id: '/de/'
      path: '/de'
      fullPath: '/de/'
      preLoaderRoute: typeof DeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/de/$slug': {
      id: '/de/$slug'
      path: '/de/$slug'
      fullPath: '/de/$slug'
      preLoaderRoute: typeof DeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visit': {
      id: '/api/visit'
      path: '/api/visit'
      fullPath: '/api/visit'
      preLoaderRoute: typeof ApiVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/territories/': {
      id: '/admin/territories/'
      path: '/territories'
      fullPath: '/admin/territories/'
      preLoaderRoute: typeof AdminTerritoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/owners/': {
      id: '/admin/owners/'
      path: '/owners'
      fullPath: '/admin/owners/'
      preLoaderRoute: typeof AdminOwnersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/campaigns/': {
      id: '/admin/campaigns/'
      path: '/campaigns'
      fullPath: '/admin/campaigns/'
      preLoaderRoute: typeof AdminCampaignsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/new': {
      id: '/admin/pages/new'
      path: '/pages/new'
      fullPath: '/admin/pages/new'
      preLoaderRoute: typeof AdminPagesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/$pageId': {
      id: '/admin/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/admin/pages/$pageId'
      preLoaderRoute: typeof AdminPagesPageIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPagesPageIdRoute: typeof AdminPagesPageIdRoute
  AdminPagesNewRoute: typeof AdminPagesNewRoute
  AdminCampaignsIndexRoute: typeof AdminCampaignsIndexRoute
  AdminOwnersIndexRoute: typeof AdminOwnersIndexRoute
  AdminTerritoriesIndexRoute: typeof AdminTerritoriesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPagesPageIdRoute: AdminPagesPageIdRoute,
  AdminPagesNewRoute: AdminPagesNewRoute,
  AdminCampaignsIndexRoute: AdminCampaignsIndexRoute,
  AdminOwnersIndexRoute: AdminOwnersIndexRoute,
  AdminTerritoriesIndexRoute: AdminTerritoriesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  LegalNoticeRoute: LegalNoticeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ApiVisitRoute: ApiVisitRoute,
  DeSlugRoute: DeSlugRoute,
  DeIndexRoute: DeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
